#!/usr/bin/with-contenv bash
# shellcheck shell=bash

umask "${UMASK}"

# shellcheck disable=SC2086
exec s6-setuidgid hotio mono --debug "${APP_DIR}/NzbDrone.exe" --nobrowser --data="${CONFIG_DIR}" ${ARGS}
